Repository Mister-Muffin/Karambolage, pull requests merged in 2019-08, with the labels that each got.

#6 Update README.md
  README.md
Labels: enhancement

#14 DaKie206 improvements
  player/Player.tscn
  scenes/Level.tscn
  scenes/ModeButton.tscn
  scenes/Restart.tscn
  scenes/Splash.tscn
  scenes/Start.tscn
  scripts/Level/Level.gd
  scripts/Level/labelTime.gd
  scripts/Splash.gd
  scripts/Start/Start.gd
  scripts/Start/btnPlay.gd
  scripts/player/Player.gd
  textures/light.png
Labels: bug, enhancement, fixed

#15 Update Start.tscn
  scenes/Start.tscn
Labels: enhancement

#16 Improvements
  scenes/Level.tscn
  scenes/Start.tscn
  scenes/closeopenAnim.tscn
  scripts/Level/contdownLabel.gd
  scripts/Start/swipe.gd
  scripts/player/Player.gd
Labels: enhancement

#17 Improvements
  globals.gd
  project.godot
  scenes/Background.tscn
  scenes/Splash.tscn
  scenes/Start.tscn
  scripts/Splash.gd
  scripts/Start/Start.gd
  scripts/Start/btnPlay.gd
Labels: enhancement, fixed

#19 Improvement
  scenes/Level.tscn
  scenes/Start.tscn
Labels: enhancement

#21 Major improvements
  enemy/Enemy.tscn
  globals.gd
  scenes/Level.tscn
  scenes/Start.tscn
  scripts/Start/Start.gd
  textures/whiteProgress.jpg
  textures/whiteProgress.jpg.import
Labels: enhancement, fixed

#22 Update README.md
  README.md
Labels: documentation, enhancement

#23 Much more Improvements:
  globals.gd
  scenes/Level.tscn
  scenes/Restart.tscn
  scenes/Start.tscn
  scripts/Level/Level.gd
  scripts/Level/keyBindingCanvas.gd
  scripts/Level/labelFPS.gd
  scripts/Level/labelTime.gd
  scripts/player/Player.gd
Labels: enhancement, fixed

#25 Update Level.tscn
  scenes/Level.tscn
Labels: fixed

#29 DaKie206
  globals.gd
  scenes/Level.tscn
  scripts/Level/pauseMenu.gd
Labels: fixed

#31 Aligned Logo new
  scenes/Start.tscn
  scripts/Start/Start.gd
Labels: enhancement

#38 Update README.md
  README.md
Labels: documentation

#41 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#35 More important improvements
  .gitignore
  config.cfg
  enemy/Enemy.tscn
  globals.gd
  items/Bullet.gd
  items/Bullet.tscn
  items/Health.gd
  items/Health.tscn
  items/gun/gun.gd
  items/gun/gun.tscn
  player/Player.tscn
  project.godot
  scenes/IconButton.tscn
  scenes/Item.tscn
  scenes/ItemSpawner.tscn
  scenes/Level.tscn
  scenes/ModeButton.tscn
  scenes/ReleaseToQuit.tscn
  scenes/Restart.tscn
  scenes/Start.tscn
  scenes/enemyParticles.tscn
  scenes/inventorySlot.bak.tscn
  scenes/inventorySlot.tscn
  scripts/IconButton.gd
  scripts/Inventory.gd
  scripts/Item.gd
  scripts/ItemSpawner.gd
  scripts/Level/Level.gd
  scripts/Level/closeAnimTween.gd
  scripts/Level/healthBar.gd
  scripts/Level/labelFPS.gd
  scripts/Level/pauseMenu.gd
  scripts/Settings.gd
  scripts/Start/Start.gd
  scripts/Start/settingsContainer.gd
  scripts/Start/sideBoard.gd
  scripts/enemy/Enemy.gd
  scripts/enemyParticles.gd
  scripts/inventorySlot.gd
  scripts/player/Player.gd
  textures/black/outline_settings_black_48dp.png
  textures/black/outline_settings_black_48dp.png.import
  textures/health.png
  textures/health.png.import
  textures/invSlot.png
  textures/invSlot.png.import
  textures/white/outline_settings_white_48dp.png
  textures/white/outline_settings_white_48dp.png.import
  themes/sideBoardTheme.tres
  themes/theme.tres
Labels: Revision needed, enhancement, fix

#48 DaKie206 patch 2
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#50 DaKie's improvements
  globals.gd
  scenes/Level.tscn
  scenes/Start.tscn
  scripts/Level/healthBar.gd
Labels: enhancement

#51 Actions
  .github/main.workflow
Labels: enhancement
